### ISSUE TITLE
Magento & Docker Cloud

### ISSUE THREAD

**Issue by Carpena** [mageinferno/magento2-stackfile#1]
Hi, 

I'm a newbie so please forgive if this is the wrong place to post this.
I've used this stackfile to create a stack on Digital Ocean though Docker Cloud.
After some fiddling, I've managed to to get it running - If I go to the Setup service it says it's installed and is running, so it stops.
The APP, the PHP-FPM and DB are running and seem to be fine.
But If I go the URL(or IP) it shows the Nginx 404 not found. So I can't access magento.

Would anyone be able to provide any clues?
Many thanks!

**Comment by markshust** [comment]
This is a place for bugs or issue reports, not for tech support. Please ask on something like stackoverflow.com

**Comment by markshust** [comment]
FYI try just restarting the php instance. The setup instance is only intended to be ran once and then disgarded.

**Comment by Carpena** [comment]
Apologies for this and thanks for your support!
